name: find_me_and_my_theme
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.2.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  equatable: ^2.0.7
  geocoding: ^4.0.0
  dio: ^5.9.0
  uuid: ^4.5.1
  dartz: ^0.10.1
  flutter_polyline_points: ^3.1.0
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 200
